/* CAUTION
   DO NOT EDIT THIS FILE,
   UNLESS YOU HAVE A VERY GOOD REASON 
 */

#ifndef _morpho_h_
#define _morpho_h_

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

#include <string.h>
#include <typedefs.h>







extern void BinaryDilation_u8 ( void* inputBuf, /* buffer to be resampled */
				 void* resultBuf, /* result buffer */
				 int *theDim, /* dimensions of this buffer */
				 int connectivity, /* connectivity to be used */ 
				 int iterations  /* number of iterations */ );






extern void BinaryErosion_u8 ( void* inputBuf, /* buffer to be resampled */
				 void* resultBuf, /* result buffer */
				 int *theDim, /* dimensions of this buffer */
				 int connectivity, /* connectivity to be used */ 
				 int iterations  /* number of iterations */ );






extern void GreyLevelDilation_u8 ( void* inputBuf, /* buffer to be resampled */
				 void* resultBuf, /* result buffer */
				 int *theDim, /* dimensions of this buffer */
				 int connectivity, /* connectivity to be used */ 
				 int iterations  /* number of iterations */ );






extern void GreyLevelErosion_u8 ( void* inputBuf, /* buffer to be resampled */
				 void* resultBuf, /* result buffer */
				 int *theDim, /* dimensions of this buffer */
				 int connectivity, /* connectivity to be used */ 
				 int iterations  /* number of iterations */ );






extern void GreyLevelDilation_r32 ( void* inputBuf, /* buffer to be resampled */
				 void* resultBuf, /* result buffer */
				 int *theDim, /* dimensions of this buffer */
				 int connectivity, /* connectivity to be used */ 
				 int iterations  /* number of iterations */ );






extern void GreyLevelErosion_r32 ( void* inputBuf, /* buffer to be resampled */
				 void* resultBuf, /* result buffer */
				 int *theDim, /* dimensions of this buffer */
				 int connectivity, /* connectivity to be used */ 
				 int iterations  /* number of iterations */ );






extern void GreyLevelDilation_u16 ( void* inputBuf, /* buffer to be resampled */
				 void* resultBuf, /* result buffer */
				 int *theDim, /* dimensions of this buffer */
				 int connectivity, /* connectivity to be used */ 
				 int iterations  /* number of iterations */ );






extern void GreyLevelErosion_u16 ( void* inputBuf, /* buffer to be resampled */
				 void* resultBuf, /* result buffer */
				 int *theDim, /* dimensions of this buffer */
				 int connectivity, /* connectivity to be used */ 
				 int iterations  /* number of iterations */ );






extern void GreyLevelDilation_s16 ( void* inputBuf, /* buffer to be resampled */
				 void* resultBuf, /* result buffer */
				 int *theDim, /* dimensions of this buffer */
				 int connectivity, /* connectivity to be used */ 
				 int iterations  /* number of iterations */ );






extern void GreyLevelErosion_s16 ( void* inputBuf, /* buffer to be resampled */
				 void* resultBuf, /* result buffer */
				 int *theDim, /* dimensions of this buffer */
				 int connectivity, /* connectivity to be used */ 
				 int iterations  /* number of iterations */ );






#ifdef __cplusplus
}
#endif

#endif
